from tkinter import *
from tkinter.ttk import *

root=Tk()
root.geometry("800x700")
root.title("Address Book")
def add():
    listbox.insert(END,str(name_box.get()))
name_Label=Label(root,text="Name:")
address_Label=Label(root,text="Address:")
age_Label=Label(root,text="Age:")
email_Label=Label(root,text="Email:")
name_box=Entry(root)
address_box=Entry(root)
age_box=Entry(root)
email_box=Entry(root)
listbox=Listbox(root,width=50,height=19)
add_button=Button(root,text="Update/Add",width=23,command=add)
delete_button=Button(root,text="Delete",width=23)
save_button=Button(root,text="Save",width=23)
edit_button=Button(root,text="Edit",width=23)
open_button=Button(root,text="Open",width=23)


name_Label.place(x=500,y=100)
address_Label.place(x=500,y=200)
age_Label.place(x=500,y=300)
email_Label.place(x=500,y=400)
name_box.place(x=550,y=100)
address_box.place(x=550,y=200)
age_box.place(x=550,y=300)
email_box.place(x=550,y=400)
listbox.place(x=100,y=50)
open_button.place(x=650,y=10)
save_button.place(x=100,y=10)
edit_button.place(x=100,y=360)
delete_button.place(x=100,y=390)
add_button.place(x=500,y=450)
root.mainloop()